apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scala-api-deployment
spec:
  selector:
    matchLabels:
      app: scala-api
  replicas: 1
  template:
    metadata:
      labels:
        app: scala-api
    spec:
      containers:
        - name: scala-api
          image: stuartloxton/scala-api:0.1
          ports:
            - containerPort: 9000
